config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :users
  resources :venues
  resources :events
  resources :attractions

  get 'tickets/guest', to: 'tickets#new_w_guest'
  post 'tickets/guest', to: 'tickets#create_w_guest'

  resources :tickets, only: [:new, :create, :show]

  root to: "welcome#home"

  get 'search', to: 'search#results'
  post 'search', to: 'search#results'

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "signup", to: "users#new"
  delete "logout", to: "sessions#destroy"

  get "music_events", to: "categories#music_events"
  get "sports_events", to: "categories#sports_events"
  get "arts_events", to: "categories#arts_events"
  get "misc_events", to: "categories#misc_events"

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :authorize

  def new
    if flash[:id]
      @event = Event.find(flash[:id])
    else
      @event = Event.find(params[:id])
    end
  end

  def create
    if !!current_user.cc_number
      i = params[:ticket][:count].to_i
      @event = Event.find(params[:id])
      i.times do
        current_user.buy_ticket(@event)
      end
      redirect_to user_path(current_user)
    else
      flash[:msg] = "You need a valid a Credit Card to purchase tickets"
      @event = Event.find(params[:id])
      flash[:id] = @event.id
      redirect_to new_ticket_path
    end
  end


  def new_w_guest
    create_guest
    @event = Event.find(params[:id])
  end

  def create_w_guest
    i = params[:ticket][:count].to_i
    @event = Event.find(params[:id])
    @user = User.find(guest_user.id)

    @user.update(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      address: params[:address],
      address2: params[:address2],
      city: params[:city],
      state: params[:state],
      postal_code: params[:postal_code],
      cc_number: params[:cc_number],
      cc_expiration: params[:cc_expiration],
      cc_name: params[:cc_name],
      cc_security_code: params[:cc_security_code]
    )
    @user.save(:validate => false)

    i.times do
      @ticket = @user.buy_ticket(@event)
    end

    redirect_to ticket_path(@ticket)
  end


  def show
    @ticket = Ticket.find(params[:id])
    @tickets = Ticket.where(user: guest_user)
    @user = guest_user
  end


end

app/views/tickets/new.html.erb
<% if flash[:msg] %>
  <%= flash[:msg] %>
  <% end %>

<br><br>

<%= @event.name %> <br>
<%= @event.start_date %> <br>
<%= @event.venue.name %>, <%= @event.venue.city %>, <%= @event.venue.state %> <br>

<br><br>



<% if loggedin? %>

what are you looking for today? <br>
<br><br>
<%= form_tag tickets_path do %>
<%= hidden_field_tag 'id', @event.id %>
How many tickets?<br>
<%= select_tag "ticket[count]", options_for_select((1..20).to_a), class: "form-controller" %> <br>
<br><br>
What is your budget per ticket? <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= @event.price_min %> <!-- @event.price_max when available --> <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= rand(50..150) %> <!-- or maybe a random selection of three between prices --> <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= rand(150..300) %>
<br><br>
<%= button_tag "Buy tickets", class: "btn img-rounded bg-primary text-light mx-5 px-5" %>
<% end %>

<% else %>

<%= form_tag tickets_guest_path, method: :get do %>
<%= hidden_field_tag 'id', @event.id %>
<br><br>
<%= button_tag "Purchase as Guest", class: "btn img-rounded bg-primary text-light mx-5 px-5" %>
<% end %> <br>
<%= form_tag login_path do %>
<%= button_tag "Sign In", class: "btn img-rounded bg-primary text-light mx-5 px-5" %>
<% end %> <br>

<% end %>

app/views/tickets/new_w_guest.html.erb
Fill in payment information!


page that has form for user with tickets to purchase and ends


<%= form_tag "/tickets/guest" do %>
How many tickets?<br>
<%= select_tag "ticket[count]", options_for_select((1..20).to_a), class: "form-controller" %> <br>
<br><br>
What is your budget per ticket? <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= @event.price_min %> <!-- @event.price_max when available --> <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= rand(50..150) %> <!-- or maybe a random selection of three between prices --> <br>
<%= radio_button_tag "ticket[price]", "#{@event.price_min}" %>
$<%= rand(150..300) %> <br><br>
Billing Information <br> <br>
<%= text_field_tag :first_name, nil, placeholder: "First Name" %> <br>
<%= text_field_tag :last_name, nil, placeholder: "Last Name" %> <br>
<%= text_field_tag :email, nil, placeholder: "Email" %> <br>
<%= label_tag "Date of birth" %>
<%= date_select :birth_date, nil, start_year: 1900 %> <br>
<%= text_field_tag :address, nil, placeholder: "Address" %> <br>
<%= text_field_tag :address2, nil, placeholder: "Address 2" %> <br>
<%= text_field_tag :city, nil, placeholder: "City" %> <br>
<%= text_field_tag :state, nil, placeholder: "State" %> <br>
<%= number_field_tag :postal_code, nil, placeholder: "Postal Code" %> <br>
<%= text_field_tag :cc_name, nil, placeholder: "Name on Credit Card" %> <br>
<%= number_field_tag :cc_number, nil, placeholder: "Credit Card Number" %> <br>
<%= date_select :cc_expiration, nil, start_year: 2018 %> <br>
<%= number_field_tag :cc_security_code, nil, placeholder: "Security Code" %> <br>
<%= hidden_field_tag 'id', @event.id %>


<br><br>
<%= button_tag "Buy tickets", class: "btn img-rounded bg-primary text-light mx-5 px-5" %>
<% end %>

app/views/tickets/show.html.erb
This is the page you should land on to show your purchased tickets


<h3>Thank you for your purchase</h3>


<%= @tickets.count %> ticket(s) to

<%= @ticket.event.name %> <br>
<%= @ticket.event.start_date %> <br>
<%= @ticket.event.venue.name %>,
<%= @ticket.event.venue.city %>
<%= @ticket.event.venue.state %>

<br><br><br>

<%= @user.first_name %> <br>
<%= @user.last_name %> <br>
<%= @user.email %> <br>
<%= @user.address %> <br>
<%= @user.address2 %> <br>
<%= @user.city %> <br>
<%= @user.state %> <br>
<%= @user.postal_code %> <br>

<br><br>
Would you like to sign up?

<%= form_tag login_path(@user) do %>
<%= button_tag "Finish Sign Up", class: "btn img-rounded bg-primary text-light mx-5 px-5" %>
<% end %>