config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :users
  resources :venues
  resources :events
  resources :attractions

  get 'tickets/guest', to: 'tickets#new_w_guest'
  post 'tickets/guest', to: 'tickets#create_w_guest'

  resources :tickets, only: [:new, :create, :show]

  root to: "welcome#home"

  get 'search', to: 'search#results'
  post 'search', to: 'search#results'

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "signup", to: "users#new"
  delete "logout", to: "sessions#destroy"

  get "music_events", to: "categories#music_events"
  get "sports_events", to: "categories#sports_events"
  get "arts_events", to: "categories#arts_events"
  get "misc_events", to: "categories#misc_events"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <div class="nav navbar  bg-dark text-light">
    <div class="container">
      <div class="row">


        <div class="col-sm">
          <%= link_to "Home", root_url %>
        </div>



        <div class="col-sm">
          <form action="/search">
            <input name="format" placeholder="Music, Sports, Arts & Theatre">
            <input type="submit" value="search" >
          </form>
        </div>



        <div class="col-sm">
          <div class="dropdown">
            <button class="btn bg-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </button>
            <div class="dropdown-menu pull-right" aria-labelledby="dropdownMenuButton">

              <% if loggedin? %>
              <%= button_to "Log out", logout_path, class: "btn img-rounded bg-primary text-light mx-5 px-5", method: :delete %>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <% else %>
              <%= button_to "Sign In", login_path, class: "btn img-rounded bg-primary text-light mx-5 px-5", method: :get %>
              <%= link_to "Edit Profile", login_path, class: "dropdown-item" %>
              <% end %>

              <a class="dropdown-item" href="#">VIEW TICKETS</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>





<!-- second nav bar below -->

  <div class="nav navbar bg-secondary text-light">

    <% if loggedin? %>
    Hello <%= current_user.first_name %>!
    <% end %>


      <%= link_to "Music", music_events_url, class: "text-light" %>

      <%= link_to "Sports", sports_events_url, class: "text-light" %>

      <%= link_to "Arts", arts_events_url, class: "text-light" %>

      <%= link_to "Miscellaneous Events", misc_events_url, class: "text-light" %>



    <% Attraction.all.any? do |att| %>
      <% if current_page?(attraction_path(att)) %>
        <%= link_to "All Attractions", attractions_path, class: "text-light" %>
      <% end %>
    <% end %>

    <% Event.all.each do |att| %>
      <% if current_page?(event_path(att)) %>
        <%= link_to "All Events", events_path, class: "text-light" %>
      <% end %>
    <% end %>

    <% Venue.all.each do |att| %>
      <% if current_page?(venue_path(att)) %>
        <%= link_to "All Venues", venues_path, class: "text-light" %>
      <% end %>
    <% end %>

  </div>




  <body>
    <%= yield %>
  </body>
</html>